### ISSUE TITLE
Persist on Member types does not create a member if it doesnt exist...

### ISSUE THREAD

**Issue by sacredgeometry** [DanMannMann/UmbracoCodeFirst#5]
Please make check to see if member exists and if it does not run

membersService.CreateMemberWithIdentity()

Kind Regards

Brian

**Comment by DanMannMann** [comment]
Changed the private IMember CreateContent(... method to use CreateMemberWithIdentity instead of CreateMember. Should resolve the issue but does mean twice the number of DB operations to create a new member as .Save() is called later on in the flow. Will consider passing a state out to control whether the 2nd .Save() call is made.
